DeveloperAcademy-POSTECH/Algorithm

- TEAM B - Afternoon/Week 1/Celan/week1(bruteforce).md
4문항 풀이
- 2003
- 1476
- 4673
- 2309
> [Update] week1 bruteforce

- TEAM B - Afternoon/Week 1/Soda/[백준 - 1018] 체스판 다시 칠하기/1018.swift
- TEAM B - Afternoon/Week 1/Soda/[백준 - 19532] 수학은 비대면강의입니다/19532.swift
- TEAM B - Afternoon/Week 1/Soda/[백준 - 2798] 블랙잭/2798.swift
> [1주차] Soda

- TEAM B - Afternoon/Week 1/Swimmer/[백준 10448]유레카이론.swift
1주차 브루트포스
- 3085
- 10448
- 14717
> swimmer 1주차

- TEAM B - Morning/Week 1/Hayo/[1주차] 하요.swift
> [1주차] Hayo

- TEAM B - Afternoon/Week 2/Swimmer/[백준 10814]나이순정렬.swift
- TEAM B - Afternoon/Week 2/Swimmer/[백준 1181]단어정렬.swift
- TEAM B - Afternoon/Week 2/Swimmer/[프로그래머스]K번째수.swift
[정렬 / 구현 문제]
-  백준 1181
- 백준 10814
- 프로그래머스 k번째 수
> [2주차]Swimmer

- TEAM B - Afternoon/Week 2/Madeline/1333.py
- TEAM B - Afternoon/Week 2/Madeline/2578.py
- TEAM B - Afternoon/Week 2/Madeline/2979.py
[구현] 
- 백준 1333번
- 백준 2979번
- 백준 2578번(미완)
> [2주차] Madeline

- TEAM B - Afternoon/Week 2/Benny/[백준-1244]스위치 켜고 끄기.py
- TEAM B - Afternoon/Week 2/Benny/[백준-1966]프린터 큐.py
- TEAM B - Afternoon/Week 2/Benny/[백준-3048]개미.py
병합 과정에서 문제가 조금 생겼는데 해결할 시간이 없어 그냥 다시 새롭게 fork repo를 만들었습니다. Week2 코드 공유합니다.
> [Add] Week2

- TEAM B - Morning/Week 2/Ddan/[백준 - 14467] 소가 길을 건너간 이유1/14467.swift
- TEAM B - Morning/Week 2/Ddan/[백준 - 1475] 방번호/1475.swift
- TEAM B - Morning/Week 2/Ddan/[백준 - 5597] 과제 안 내신 분..?/5597.swift
- TEAM B - Morning/Week 3/Ddan/[백준 - 11866] 요세푸스 문제0/11866.swift
- TEAM B - Morning/Week 3/Ddan/[백준 - 1966] 프린터 큐/1966.swift
> Ddan 2주차, 3주차

- TEAM B - Afternoon/Week3/Swimmer/[백준 10816]숫자카드2.py
- TEAM B - Afternoon/Week3/Swimmer/[백준 2805]나무자르기.py
- TEAM B - Afternoon/Week3/Swimmer/[이코테]부품찾기.py
`[3주차] 이진탐색`
- [백준 10816] 숫자카드2
- [백준 2805] 나무자르기
- [이코테] 부품 찾기
> [Swimmer] 3주차 3문제

- TEAM B - Afternoon/Week 3/Madeline/1072.py
- TEAM B - Afternoon/Week 3/Madeline/10815.py
- TEAM B - Afternoon/Week 3/Madeline/2805.py
- TEAM B - Afternoon/Week 4/Madeline/4949.py
- TEAM B - Afternoon/Week 4/Madeline/프로그래머스_같은 숫자는 싫어.py
- TEAM B - Afternoon/Week 4/Madeline/프로그래머스_기능개발.py
[3주차] 이진탐색
- 백준 10815 숫자카드
- 백준 2805 나무 자르기
- 백준 1072 게임
[4주차] 스택/큐
- 백준 4949 올바른 괄호
- 프로그래머스 같은 숫자는 싫어
- 프로그래머스 기능개발
> [3주차], [4주차] 매들린

- TEAM A/Week 4/Poodle/[백준 - 1043] 거짓말/1043.py
- TEAM A/Week 4/Poodle/[백준 - 1043] 거짓말/풀이.md
- TEAM A/Week 4/Poodle/[백준 - 17142] 연구소 3/17142.py
- TEAM A/Week 4/Poodle/[백준 - 17142] 연구소 3/풀이.md
- TEAM A/Week 4/Poodle/[백준 - 2143] 두 배열의 합/2143.py
- TEAM A/Week 4/Poodle/[백준 - 2143] 두 배열의 합/풀이.md
> [4주차] Poodle

- TEAM B - Morning/Week 3/azhy/숫자_정사각형.java
- TEAM B - Morning/Week 3/azhy/요세푸스_문제.java
- TEAM B - Morning/Week 3/azhy/점프왕_쩰리_16173.java
> [3주차] azhy

- TEAM B - Afternoon/Week 9/Swimmer/[백준 1753] 최단경로.py
> [9주차] Swimmer

- TEAM B - Afternoon/Week 10/Lets/Free/프로그래머스/distance_check
- TEAM B - Afternoon/Week 10/Lets/Free/프로그래머스/rotate_matrix_edges.py
10주차 자율문제
프로그래머스
- 사회적 거리두기
- 행렬 돌리기
> [10주차] 자율문제

- TEAM A (Season 1, 2)/Week 10/Poodle/[백준 - 1360] 되돌리기/1360.py
- TEAM A (Season 1, 2)/Week 10/Poodle/[백준 - 1360] 되돌리기/풀이.md
- TEAM A (Season 1, 2)/Week 10/Poodle/[백준 - 14890] 경사로/14890.py
- TEAM A (Season 1, 2)/Week 10/Poodle/[백준 - 14890] 경사로/풀이.md
- TEAM A (Season 1, 2)/Week 10/Poodle/[백준 - 2252] 줄 세우기/2252.py
- TEAM A (Season 1, 2)/Week 10/Poodle/[백준 - 2252] 줄 세우기/풀이.md
- TEAM A (Season 1, 2)/Week 10/Poodle/[백준 - 2623] 음악프로그램/2623.py
- TEAM A (Season 1, 2)/Week 10/Poodle/[백준 - 2623] 음악프로그램/풀이.md
위상 정렬은 처음 풀어 봤는데, 공교롭게 두 분이 위상 정렬 문제를 추천해 주셔서 확실하게 이해할 수 있었습니다!
9주차 문제는 **홍익 투어리스트**에 치여서 아직 풀이 중입니다... 10주차 먼저 PR 제출할게요!!
> [10주차] Poodle

- TEAM B2 (Season 2)/Week 1/Musk/[완전탐색_모음사전].cpp
- TEAM B2 (Season 2)/Week 1/Musk/[완전탐색_모의고사].cpp
- TEAM B2 (Season 2)/Week 1/Musk/[완전탐색_최소직사각형].cpp
- TEAM B2 (Season 2)/Week 1/Musk/[완전탐색_카펫].cpp
> Team B2_Musk_week1

- TEAM B2 (Season 2)/Week 1/Ollie/[완전탐색_모의고사].py
- TEAM B2 (Season 2)/Week 1/Ollie/[완전탐색_소수찾기].py
- TEAM B2 (Season 2)/Week 1/Ollie/[완전탐색_전력망].py
- TEAM B2 (Season 2)/Week 1/Ollie/[완전탐색_최소직사각형].py
- TEAM B2 (Season 2)/Week 1/Ollie/[완전탐색_카펫].py
> [1주차] Ollie

- TEAM B - Afternoon/Week 13/Madeline/11049.cpp
- TEAM B - Afternoon/Week 13/Madeline/1541.cpp
- TEAM B - Afternoon/Week 13/Madeline/1654.cpp
- TEAM B - Afternoon/Week 13/Madeline/2559.cpp
공통문제
- [1541] 잃어버린 괄호
- [1654] 랜선 자르기
- [2599] 수열
- [11049] 행렬곱
> [13주차] Madeline

- TEAM A (Season 1, 2)/Week 11/Poodle/[백준 - 11049] 행렬 곱셈 순서/11049.py
- TEAM A (Season 1, 2)/Week 11/Poodle/[백준 - 11049] 행렬 곱셈 순서/풀이.md
- TEAM A (Season 1, 2)/Week 11/Poodle/[백준 - 1520] 내리막 길/1520.py
- TEAM A (Season 1, 2)/Week 11/Poodle/[백준 - 1520] 내리막 길/풀이.md
- TEAM A (Season 1, 2)/Week 11/Poodle/[백준 - 16236] 아기 상어/16236.py
- TEAM A (Season 1, 2)/Week 11/Poodle/[백준 - 16236] 아기 상어/풀이.md
- TEAM A (Season 1, 2)/Week 11/Poodle/[백준 - 3109] 빵집/3109.py
- TEAM A (Season 1, 2)/Week 11/Poodle/[백준 - 3109] 빵집/풀이.md
무시무시한 문제들이어서 힘들었습니다.
그리고 9주차 **홍익 투어리스트** 문제는 왜 C++이랑 같은 알고리즘으로 구현했는데도 시간 초과가 날까요...ㅠ
빨리 PR 올리고 싶네요 정말...
> [11주차] Poodle

- TEAM B - Afternoon/Week 14/Madeline/1012.cpp
- TEAM B - Afternoon/Week 14/Madeline/11053.cpp
- TEAM B - Afternoon/Week 14/Madeline/15663.cpp
- TEAM B - Afternoon/Week 14/Madeline/2467.cpp
- TEAM B - Afternoon/Week 14/Madeline/2512.cpp
- 2467 용액
- 1012 유기농 배추
- 11053 가장 긴 증가하는 부분 수열
- 15663 N과 M(9)
- 2512 예산
> [14주차] Madeline

- Team C (Season 2)/Week 1/Chaekie/carpet.py
- Team C (Season 2)/Week 1/Chaekie/findPrimeNumber.py
- Team C (Season 2)/Week 1/Chaekie/minRectangle.py
- Team C (Season 2)/Week 1/Chaekie/mockTest.py
> week1 완전탐색 4문제

- TEAM B - Afternoon, TEAM B1 (Season 1, 2)/Week 13/Soda/11049.swift
- TEAM B - Afternoon, TEAM B1 (Season 1, 2)/Week 14/Soda/11053.swift
- TEAM B - Afternoon, TEAM B1 (Season 1, 2)/Week 14/Soda/15663.swift
- TEAM B - Afternoon, TEAM B1 (Season 1, 2)/Week 14/Soda/2512.swift
> [14주차] Soda

- Team C (Season 2)/Week2/Chaekie/[스택,큐]_같은숫자는싫어.py
- Team C (Season 2)/Week2/Chaekie/[스택,큐]_기능개발.py
- Team C (Season 2)/Week2/Chaekie/[스택,큐]_다리를지나는트럭.py
- Team C (Season 2)/Week2/Chaekie/[스택,큐]_올바른괄호.py
- Team C (Season 2)/Week2/Chaekie/[스택,큐]_주식가격.py
- Team C (Season 2)/Week2/Chaekie/[스택,큐]_프로세스.py
> week2 스택, 큐

- TEAM B2 (Season 2)/Week 4/Moana/[힙_이중우선순위큐].py
- TEAM B2 (Season 2)/Week5/Moana/[정렬_H-Index].py
- TEAM B2 (Season 2)/Week5/Moana/[정렬_K번째 수].py
- TEAM B2 (Season 2)/Week5/Moana/[정렬_가장큰수].py
> Moana_week5

- TEAM B - Afternoon/Week 17/Madeline/1107.cpp
- TEAM B - Afternoon/Week 17/Madeline/1987.cpp
- TEAM B - Afternoon/Week 17/Madeline/프로그래머스_주차요금계산.cpp
BOJ
- 1107
- 1987 
프로그래머스
- 주차요금계산
> [17주차] Madeline
